import { prisma } from './prisma';

/**
 * ISO 27001 Audit Logging Utility
 */
export async function logSecurityAction(params: {
  tenantId: string;
  userId?: string;
  action: string;
  resource?: string;
  details?: any;
  ipAddress?: string;
}) {
  try {
    await prisma.securityLog.create({
      data: {
        tenantId: params.tenantId,
        userId: params.userId,
        action: params.action,
        resource: params.resource,
        details: params.details || {},
        ipAddress: params.ipAddress
      }
    });
  } catch (error) {
    console.error('FAILED_TO_LOG_SECURITY_ACTION:', error);
  }
}

export enum SecurityAction {
  // Authentication
  LOGIN_SUCCESS = 'LOGIN_SUCCESS',
  LOGIN_FAILED = 'LOGIN_FAILED',
  LOGOUT = 'LOGOUT',
  PASSWORD_CHANGE = 'PASSWORD_CHANGE',
  PASSWORD_RESET = 'PASSWORD_RESET',

  // User Management
  USER_CREATED = 'USER_CREATED',
  USER_UPDATED = 'USER_UPDATED',
  USER_DELETED = 'USER_DELETED',
  USER_ROLE_CHANGED = 'USER_ROLE_CHANGED',
  PERMISSIONS_UPDATED = 'PERMISSIONS_UPDATED',

  // Custom Roles
  ROLE_CREATED = 'ROLE_CREATED',
  ROLE_UPDATED = 'ROLE_UPDATED',
  ROLE_DELETED = 'ROLE_DELETED',

  // Data Operations
  SENSITIVE_DATA_UPDATE = 'SENSITIVE_DATA_UPDATE',
  CREDENTIAL_ENCRYPTION = 'CREDENTIAL_ENCRYPTION',
  DATA_EXPORT = 'DATA_EXPORT',
  BULK_DELETE = 'BULK_DELETE',

  // Inventory
  PRODUCT_CREATED = 'PRODUCT_CREATED',
  PRODUCT_UPDATED = 'PRODUCT_UPDATED',
  PRODUCT_DELETED = 'PRODUCT_DELETED',
  STOCK_ADJUSTMENT = 'STOCK_ADJUSTMENT',
  STOCK_TRANSFER = 'STOCK_TRANSFER',

  // Invoicing
  INVOICE_CREATED = 'INVOICE_CREATED',
  INVOICE_UPDATED = 'INVOICE_UPDATED',
  INVOICE_VOIDED = 'INVOICE_VOIDED',
  PAYMENT_RECORDED = 'PAYMENT_RECORDED',

  // GST & Compliance
  GSP_API_ACCESS = 'GSP_API_ACCESS',
  EXPORT_GSTR1 = 'EXPORT_GSTR1',
  EINVOICE_GENERATED = 'EINVOICE_GENERATED',

  // HR
  EMPLOYEE_CREATED = 'EMPLOYEE_CREATED',
  EMPLOYEE_UPDATED = 'EMPLOYEE_UPDATED',
  LEAVE_APPROVED = 'LEAVE_APPROVED',
  LEAVE_REJECTED = 'LEAVE_REJECTED',
  PAYSLIP_GENERATED = 'PAYSLIP_GENERATED',

  // Communication
  BULK_PAYMENT_REMINDER = 'BULK_PAYMENT_REMINDER',
  WHATSAPP_SENT = 'WHATSAPP_SENT',

  // Settings
  TENANT_SETTINGS_UPDATED = 'TENANT_SETTINGS_UPDATED',
  INTEGRATION_CONFIGURED = 'INTEGRATION_CONFIGURED',
  API_KEY_GENERATED = 'API_KEY_GENERATED',
  API_KEY_REVOKED = 'API_KEY_REVOKED',

  // Discounts
  DISCOUNT_CREATED = 'DISCOUNT_CREATED',
  DISCOUNT_UPDATED = 'DISCOUNT_UPDATED',
  DISCOUNT_DELETED = 'DISCOUNT_DELETED',

  // Custom Domains
  CUSTOM_DOMAIN_SET = 'CUSTOM_DOMAIN_SET',
  CUSTOM_DOMAIN_VERIFIED = 'CUSTOM_DOMAIN_VERIFIED',
  CUSTOM_DOMAIN_REMOVED = 'CUSTOM_DOMAIN_REMOVED',

  // Suppliers
  SUPPLIER_CREATED = 'SUPPLIER_CREATED',
  SUPPLIER_UPDATED = 'SUPPLIER_UPDATED',
  SUPPLIER_DELETED = 'SUPPLIER_DELETED',
}
