/* eslint-disable @typescript-eslint/no-explicit-any */

const fonts = {
  Roboto: {
    normal: 'Helvetica',
    bold: 'Helvetica-Bold',
    italics: 'Helvetica-Oblique',
    bolditalics: 'Helvetica-BoldOblique',
  },
};

async function getPrinter() {
  const pdfmakeModule = await import('pdfmake');
  const PdfPrinter = pdfmakeModule.default as any;
  return new PdfPrinter(fonts);
}

export interface POPDFData {
  poNumber: string;
  createdAt: string;
  dueDate?: string;
  paymentTerms?: string;
  notes?: string;
  // Tenant (buyer)
  tenantName: string;
  tenantAddress?: string;
  tenantGstin?: string;
  tenantPhone?: string;
  tenantEmail?: string;
  // Supplier
  supplierName: string;
  supplierAddress?: string;
  supplierGstin?: string;
  supplierPhone?: string;
  supplierEmail?: string;
  // Delivery
  deliveryLocationName?: string;
  // E-Way Bill
  ewayBillNumber?: string;
  transporterName?: string;
  vehicleNumber?: string;
  // Items
  items: Array<{
    productName: string;
    sku?: string;
    hsnCode?: string;
    orderedQty: number;
    unitCost: number;
    taxRate: number;
    total: number;
  }>;
  // Totals
  subtotal: number;
  taxAmount: number;
  shipping: number;
  total: number;
  currency: string;
}

function formatCurrency(amount: number, currency = 'INR'): string {
  const symbol = currency === 'INR' ? '₹' : currency;
  return `${symbol}${amount.toLocaleString('en-IN', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
}

export async function generatePurchaseOrderPDF(data: POPDFData): Promise<Buffer> {
  const docDefinition: any = {
    pageSize: 'A4',
    pageMargins: [40, 60, 40, 60],

    header: {
      columns: [
        {
          text: 'PURCHASE ORDER',
          style: 'header',
          margin: [40, 20, 0, 0],
        },
        {
          text: data.poNumber,
          alignment: 'right',
          style: 'poNumber',
          margin: [0, 20, 40, 0],
        },
      ],
    },

    footer: (currentPage: number, pageCount: number) => ({
      columns: [
        {
          text: 'Generated by EaseInventory',
          fontSize: 8,
          color: '#888',
          margin: [40, 0, 0, 0],
        },
        {
          text: `Page ${currentPage} of ${pageCount}`,
          alignment: 'right',
          fontSize: 8,
          color: '#888',
          margin: [0, 0, 40, 0],
        },
      ],
      margin: [0, 20, 0, 0],
    }),

    content: [
      // Date and payment info
      {
        columns: [
          { text: `Date: ${new Date(data.createdAt).toLocaleDateString('en-IN')}`, fontSize: 10, color: '#666' },
          ...(data.dueDate
            ? [{ text: `Due Date: ${new Date(data.dueDate).toLocaleDateString('en-IN')}`, fontSize: 10, color: '#666', alignment: 'right' as const }]
            : []),
        ],
        margin: [0, 0, 0, 15],
      },
      ...(data.paymentTerms
        ? [{ text: `Payment Terms: ${data.paymentTerms}`, fontSize: 10, color: '#666', margin: [0, 0, 0, 15] }]
        : []),

      // Buyer and Supplier columns
      {
        columns: [
          {
            width: '48%',
            stack: [
              { text: 'FROM (Buyer)', style: 'addressLabel' },
              { text: data.tenantName, style: 'addressName' },
              ...(data.tenantAddress ? [{ text: data.tenantAddress, fontSize: 9, color: '#555' }] : []),
              ...(data.tenantGstin ? [{ text: `GSTIN: ${data.tenantGstin}`, fontSize: 9, color: '#555' }] : []),
              ...(data.tenantPhone ? [{ text: `Phone: ${data.tenantPhone}`, fontSize: 9, color: '#555' }] : []),
              ...(data.tenantEmail ? [{ text: data.tenantEmail, fontSize: 9, color: '#555' }] : []),
            ],
          },
          { width: '4%', text: '' },
          {
            width: '48%',
            stack: [
              { text: 'TO (Supplier)', style: 'addressLabel' },
              { text: data.supplierName, style: 'addressName' },
              ...(data.supplierAddress ? [{ text: data.supplierAddress, fontSize: 9, color: '#555' }] : []),
              ...(data.supplierGstin ? [{ text: `GSTIN: ${data.supplierGstin}`, fontSize: 9, color: '#555' }] : []),
              ...(data.supplierPhone ? [{ text: `Phone: ${data.supplierPhone}`, fontSize: 9, color: '#555' }] : []),
              ...(data.supplierEmail ? [{ text: data.supplierEmail, fontSize: 9, color: '#555' }] : []),
            ],
          },
        ],
        margin: [0, 0, 0, 20],
      },

      // Delivery location
      ...(data.deliveryLocationName
        ? [{
            text: `Delivery Location: ${data.deliveryLocationName}`,
            fontSize: 10,
            bold: true,
            margin: [0, 0, 0, 15],
          }]
        : []),

      // Items table
      { text: 'Order Items', style: 'sectionHeader', margin: [0, 0, 0, 10] },
      {
        table: {
          headerRows: 1,
          widths: ['auto', '*', 'auto', 'auto', 'auto', 'auto', 'auto'],
          body: [
            [
              { text: '#', style: 'tableHeader' },
              { text: 'Product', style: 'tableHeader' },
              { text: 'HSN', style: 'tableHeader' },
              { text: 'Qty', style: 'tableHeader' },
              { text: 'Unit Cost', style: 'tableHeader' },
              { text: 'Tax %', style: 'tableHeader' },
              { text: 'Total', style: 'tableHeader' },
            ],
            ...data.items.map((item, idx) => [
              { text: `${idx + 1}`, fontSize: 9 },
              {
                stack: [
                  { text: item.productName, fontSize: 9, bold: true },
                  ...(item.sku ? [{ text: `SKU: ${item.sku}`, fontSize: 7, color: '#888' }] : []),
                ],
              },
              { text: item.hsnCode || '-', fontSize: 9 },
              { text: `${item.orderedQty}`, fontSize: 9, alignment: 'right' as const },
              { text: formatCurrency(item.unitCost, data.currency), fontSize: 9, alignment: 'right' as const },
              { text: `${item.taxRate}%`, fontSize: 9, alignment: 'center' as const },
              { text: formatCurrency(item.total, data.currency), fontSize: 9, alignment: 'right' as const, bold: true },
            ]),
          ],
        },
        layout: {
          fillColor: (rowIndex: number) => (rowIndex === 0 ? '#6A3BF6' : rowIndex % 2 === 0 ? '#fafafa' : null),
          hLineWidth: () => 0.5,
          vLineWidth: () => 0,
          hLineColor: () => '#e0e0e0',
          paddingLeft: () => 8,
          paddingRight: () => 8,
          paddingTop: () => 6,
          paddingBottom: () => 6,
        },
        margin: [0, 0, 0, 10],
      },

      // Totals
      {
        columns: [
          { width: '*', text: '' },
          {
            width: 200,
            table: {
              widths: ['*', 'auto'],
              body: [
                [
                  { text: 'Subtotal', fontSize: 10, color: '#666' },
                  { text: formatCurrency(data.subtotal, data.currency), fontSize: 10, alignment: 'right' as const },
                ],
                [
                  { text: 'Tax', fontSize: 10, color: '#666' },
                  { text: formatCurrency(data.taxAmount, data.currency), fontSize: 10, alignment: 'right' as const },
                ],
                ...(data.shipping > 0
                  ? [[
                      { text: 'Shipping', fontSize: 10, color: '#666' },
                      { text: formatCurrency(data.shipping, data.currency), fontSize: 10, alignment: 'right' as const },
                    ]]
                  : []),
                [
                  { text: 'TOTAL', fontSize: 12, bold: true },
                  { text: formatCurrency(data.total, data.currency), fontSize: 12, bold: true, alignment: 'right' as const },
                ],
              ],
            },
            layout: {
              hLineWidth: (i: number, node: any) => (i === node.table.body.length - 1 ? 1 : 0),
              vLineWidth: () => 0,
              hLineColor: () => '#333',
              paddingTop: () => 4,
              paddingBottom: () => 4,
            },
          },
        ],
        margin: [0, 10, 0, 20],
      },

      // E-Way Bill info
      ...(data.ewayBillNumber
        ? [{
            table: {
              widths: ['*', '*', '*'],
              body: [[
                { text: `E-Way Bill: ${data.ewayBillNumber}`, fontSize: 9 },
                { text: data.transporterName ? `Transporter: ${data.transporterName}` : '', fontSize: 9 },
                { text: data.vehicleNumber ? `Vehicle: ${data.vehicleNumber}` : '', fontSize: 9 },
              ]],
            },
            layout: {
              fillColor: () => '#f0f0f0',
              hLineWidth: () => 0,
              vLineWidth: () => 0,
              paddingLeft: () => 10,
              paddingRight: () => 10,
              paddingTop: () => 8,
              paddingBottom: () => 8,
            },
            margin: [0, 0, 0, 15],
          }]
        : []),

      // Notes
      ...(data.notes
        ? [
            { text: 'Notes', style: 'sectionHeader', margin: [0, 0, 0, 5] },
            { text: data.notes, fontSize: 9, color: '#555', margin: [0, 0, 0, 15] },
          ]
        : []),

      // Signature blocks
      {
        columns: [
          {
            width: '45%',
            stack: [
              { text: '', margin: [0, 40, 0, 0] },
              { canvas: [{ type: 'line', x1: 0, y1: 0, x2: 180, y2: 0, lineWidth: 0.5, lineColor: '#999' }] },
              { text: 'Authorized Signature (Buyer)', fontSize: 8, color: '#888', margin: [0, 5, 0, 0] },
            ],
          },
          { width: '10%', text: '' },
          {
            width: '45%',
            stack: [
              { text: '', margin: [0, 40, 0, 0] },
              { canvas: [{ type: 'line', x1: 0, y1: 0, x2: 180, y2: 0, lineWidth: 0.5, lineColor: '#999' }] },
              { text: 'Authorized Signature (Supplier)', fontSize: 8, color: '#888', margin: [0, 5, 0, 0] },
            ],
          },
        ],
      },
    ],

    styles: {
      header: {
        fontSize: 18,
        bold: true,
        color: '#6A3BF6',
      },
      poNumber: {
        fontSize: 16,
        bold: true,
        color: '#333',
      },
      addressLabel: {
        fontSize: 8,
        bold: true,
        color: '#6A3BF6',
        margin: [0, 0, 0, 4],
      },
      addressName: {
        fontSize: 12,
        bold: true,
        color: '#333',
        margin: [0, 0, 0, 3],
      },
      sectionHeader: {
        fontSize: 12,
        bold: true,
        color: '#333',
      },
      tableHeader: {
        fontSize: 8,
        bold: true,
        color: 'white',
      },
    },
  };

  const printer = await getPrinter();

  return new Promise((resolve, reject) => {
    const pdfDoc = printer.createPdfKitDocument(docDefinition);
    const chunks: Buffer[] = [];

    pdfDoc.on('data', (chunk: Buffer) => chunks.push(chunk));
    pdfDoc.on('end', () => resolve(Buffer.concat(chunks)));
    pdfDoc.on('error', reject);
    pdfDoc.end();
  });
}
