name: Feature Request
description: Request a new feature or enhancement
title: "[FEATURE]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        ## Feature Request
        Please fill out the following details to help us understand your request.

  - type: textarea
    id: user-story
    attributes:
      label: User Story
      description: Describe the feature from a user's perspective
      placeholder: "As a [role], I want to [action] so that [benefit]"
    validations:
      required: true

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: What must be true for this feature to be considered complete?
      placeholder: |
        - [ ] Criterion 1
        - [ ] Criterion 2
    validations:
      required: true

  - type: dropdown
    id: module
    attributes:
      label: Module
      description: Which module does this feature belong to?
      options:
        - Inventory Management
        - Repair & Service Center
        - Invoicing & Billing
        - Delivery Management
        - HR & Attendance
        - Users & Permissions
        - Supplier & Consignment
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature?
      options:
        - High (MVP)
        - Medium
        - Low (Nice to have)
    validations:
      required: true
